<a href="https://colab.research.google.com/github/hamusita/memo/blob/main/ml_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

PCA

In [10]:
x = np.array([[2,0],[-2,-2],[0,2]])

In [11]:
x

array([[ 2,  0],
       [-2, -2],
       [ 0,  2]])

In [12]:
np.mean(x, axis=0)

array([0., 0.])

In [13]:
cm = np.cov(x, rowvar=0, bias=0)
cm

array([[4., 2.],
       [2., 4.]])

In [14]:
np.linalg.eig(cm)

(array([6., 2.]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [16]:
np.sqrt(1/(1+(1.6056/3)**2)) * 1.6056 / 3

0.47186905686161973

In [17]:
R1 = 8.60555128 / (8.60555128 + 1.39444872)

In [18]:
R1

0.860555128

k-means

In [15]:
x = np.array([-4,3,0,-2,7,10])
c1 = 1
c2 = 2

In [16]:
DA1 = (x- c1)**2
DA1

array([25,  4,  1,  9, 36, 81])

In [17]:
DA2 = (x- c2)**2
DA2

array([36,  1,  4, 16, 25, 64])

In [26]:
np.minimum(DA1,DA2)

array([25,  1,  1,  9, 25, 64])

In [27]:
loss = np.sum(np.minimum(DA1,DA2))
loss

125

In [20]:
c1n = np.mean([-4,0,-2])
c1n

-2.0

In [21]:
c2n = np.mean([3,7,10])
c2n

6.666666666666667

In [24]:
nDA1 = (x- c1n)**2
nDA1

array([  4.,  25.,   4.,   0.,  81., 144.])

In [22]:
nDA2 = (x- c2n)**2
nDA2

array([1.13777778e+02, 1.34444444e+01, 4.44444444e+01, 7.51111111e+01,
       1.11111111e-01, 1.11111111e+01])

In [25]:
loss = np.sum(np.minimum(nDA1,nDA2))
loss

32.666666666666664

EM algorithm

In [6]:
def gauss(x, mu=0, sigma=1):
    return 1 / (np.sqrt(2*np.pi) * sigma) * np.exp(-(x - mu)**2 / (2*sigma**2))

In [9]:
gauss(6, mu=2, sigma=1)

0.00013383022576488537

In [28]:
x = np.array([[80, 90, 70,100, 80],
              [40, 50, 60, 40, 30],
              [50, 60, 80, 30,20]])

In [29]:
y = np.array([[0.1, 0.8, 0.1],
              [0.8, 0.3, 0.8],
              [0.1, 0.8, 0.1]])

In [33]:
from scipy import signal
signal.convolve2d(x, y, 'valid')

array([[243., 238., 213.]])

In [34]:
import skimage.measure

a = np.array([
      [ 0,  0,   0],
      [ 0,  99,  59],
      [ 0,  55,  65]
])
skimage.measure.block_reduce(a, (2,2), np.max)

array([[99, 59],
       [55, 65]])

In [35]:
b = np.array([
      [ 0,  0,   0],
      [ 75,  70,  73],
      [ 29,  26,  48]
])
skimage.measure.block_reduce(b, (2,2), np.max)

array([[75, 73],
       [29, 48]])